package com.smnm.englishtrackingai

object AdvancedWords {
    val list = listOf(
        // Batch 1 (A-B)
        VocabWord("Abundant", "Available in large quantities; plentiful", "The region has an abundant supply of natural water."),
        VocabWord("Accumulate", "To gather or collect gradually over time", "He managed to accumulate wealth through smart investments."),
        VocabWord("Accustomed", "Familiar with something so that it feels normal", "I am accustomed to drinking warm water in the morning."),
        VocabWord("Acquire", "To get, buy, or learn something", "It takes time to acquire a new language skill."),
        VocabWord("Adaptable", "Able to adjust to new conditions easily", "She is very adaptable and can work in any situation."),
        VocabWord("Adhere", "To stick firmly to a rule, agreement, or plan", "All members must adhere to the guidelines."),
        VocabWord("Adore", "To love and admire someone very deeply", "Children adore their grandparents for their stories."),
        VocabWord("Advocate", "To publicly support a cause or policy", "He likes to advocate for eco-friendly lifestyle habits."),
        VocabWord("Aesthetic", "Relating to beauty or pure artistic taste", "The new cafe has a very pleasant aesthetic design."),
        VocabWord("Affectionate", "Showing fondness, love, or tenderness", "The pet dog is very affectionate toward family members."),
        VocabWord("Aggressive", "Ready or likely to attack or confront", "His aggressive behavior during the game was not good."),
        VocabWord("Alleviate", "To make suffering or a problem less severe", "This medicine will help to alleviate your headache."),
        VocabWord("Alter", "To change something slightly", "We need to alter our travel plans due to rain."),
        VocabWord("Ambiguous", "Not clear; having more than one meaning", "His text message was ambiguous, so I got confused."),
        VocabWord("Ambitious", "Having a strong desire to succeed or achieve", "The young boy has ambitious plans for his career."),
        VocabWord("Ample", "More than enough space, time, or amount", "Don't rush, we have ample time to catch the train."),
        VocabWord("Amplify", "To make something stronger, louder, or bigger", "Use the microphone to amplify your voice in the hall."),
        VocabWord("Analyze", "To examine something in detail to understand it", "We need to analyze the market before launching the app."),
        VocabWord("Anticipate", "To expect or predict something in advance", "We anticipate a positive response from our clients."),
        VocabWord("Apparent", "Clearly visible or understood; obvious", "It became apparent that he was not telling the truth."),
        VocabWord("Appealing", "Attractive, interesting, or pleasing", "The food presentation looked highly appealing."),
        VocabWord("Apprehensive", "Anxious or fearful that something bad will happen", "She felt apprehensive before her first flight."),
        VocabWord("Arbitrary", "Based on random choice rather than a reason", "The teacher's decision to pick students felt arbitrary."),
        VocabWord("Arduous", "Involving a lot of effort; difficult and tiring", "Climbing the mountain peak was an arduous task."),
        VocabWord("Arrogant", "Having an exaggerated sense of self-importance", "No one likes him because he is very arrogant."),
        VocabWord("Articulate", "Able to express ideas clearly and fluently", "A good speaker must be articulate and clear."),
        VocabWord("Ascertain", "To find out something for certain", "Please ascertain the exact timing of the function."),
        VocabWord("Aspiration", "A strong hope or ambition of achieving something", "She has an aspiration to become a space scientist."),
        VocabWord("Assertive", "Having a confident and forceful personality", "You need to be assertive to lead a large team."),
        VocabWord("Astonishing", "Extremely surprising or impressive", "The magician performed an astonishing trick today."),
        VocabWord("Astute", "Sharp and clever; quick to notice things", "He made an astute business decision that saved money."),
        VocabWord("Attain", "To succeed in achieving something difficult", "You can attain success if you practice regularly."),
        VocabWord("Attribute", "A quality or feature belonging to someone", "Patience is a great attribute of a good teacher."),
        VocabWord("Audacious", "Showing a willingness to take bold risks", "The team made an audacious plan to win the match."),
        VocabWord("Authentic", "Real, genuine, and not a copy", "This restaurant serves authentic South Indian food."),
        VocabWord("Avid", "Having or showing a keen interest in something", "My brother is an avid reader of history books."),
        VocabWord("Baffle", "To totally confuse or perplex someone", "This tricky puzzle can baffle anyone easily."),
        VocabWord("Barren", "Land too poor to produce any crops or plants", "Nothing grows in this dry and barren desert area."),
        VocabWord("Benevolent", "Kind, helpful, and generous in nature", "The benevolent lady donated money to the school."),
        VocabWord("Bewilder", "To cause someone to become thoroughly confused", "The complex city roads can bewilder new tourists."),
        VocabWord("Bias", "A prejudice for or against something unfairly", "A good judge must make decisions without any bias."),
        VocabWord("Bizarre", "Very strange, unusual, or weird", "We saw a bizarre looking animal in the forest."),
        VocabWord("Blatant", "Very obvious, especially in a bad or open way", "Telling a blatant lie in court will cause trouble."),
        VocabWord("Bleak", "Lacking in warmth or hope; miserable", "The future of the old factory looks quite bleak."),
        VocabWord("Blunt", "Saying exactly what you think without being polite", "I like his blunt honesty, he never hides facts."),
        VocabWord("Boast", "To talk with excessive pride about oneself", "It is not good behavior to boast about your wealth."),
        VocabWord("Boisterous", "Noisy, energetic, and cheerful", "The boisterous crowd cheered loudly for the team."),
        VocabWord("Bold", "Showing an ability to take risks; confident", "She made a bold choice to start her own company."),
        VocabWord("Brittle", "Hard but liable to break or shatter easily", "Be careful, these antique glass cups are very brittle."),
        VocabWord("Candid", "Truthful, straightforward, and honest", "Thank you for giving your candid opinion on this."),
        // Batch 2 (C)
        VocabWord("Capable", "Having the ability or power to do something", "She is highly capable of handling this big project."),
        VocabWord("Captivate", "To hold the interest and attention of someone", "Her beautiful voice managed to captivate the entire audience."),
        VocabWord("Catalyst", "Something that causes a quick change or event", "The new policy acted as a catalyst for company growth."),
        VocabWord("Cease", "To stop happening or bring to an end", "The heavy rain finally ceased in the evening."),
        VocabWord("Chronological", "Arranged in the order of time", "Please arrange these historical events in chronological order."),
        VocabWord("Circumspect", "Cautious and unwilling to take risks", "Officials are very circumspect about making public statements."),
        VocabWord("Clarity", "The quality of being clear and easy to understand", "There is a lack of clarity in the new set of rules."),
        VocabWord("Cognitive", "Relating to the mental process of thinking and learning", "Playing chess helps to improve cognitive skills in children."),
        VocabWord("Coherent", "Logical, clear, and easy to understand", "He failed to give a coherent explanation for his absence."),
        VocabWord("Coincidence", "A remarkable event happening by chance at the same time", "Meeting my old school teacher in London was a pure coincidence."),
        VocabWord("Commendable", "Deserving praise or approval", "Your dedication to teaching poor kids is truly commendable."),
        VocabWord("Compelling", "Very interesting or convincing", "The lawyer presented a compelling argument in the court."),
        VocabWord("Compensate", "To make up for something lost or damaged", "The company will compensate you for the extra hours worked."),
        VocabWord("Competent", "Having the necessary skill or knowledge to do a job", "We need a competent accountant to handle our finances."),
        VocabWord("Complacent", "Too satisfied with oneself without trying to improve", "Winners should never become complacent about their success."),
        VocabWord("Complement", "To add to something in a way that improves it", "This beautiful painting will complement the living room wall."),
        VocabWord("Complex", "Consisting of many different and connected parts", "The human brain has a very complex network of neurons."),
        VocabWord("Compliance", "The act of obeying a rule, law, or request", "The company is in full compliance with environmental laws."),
        VocabWord("Comprehensive", "Including or dealing with all aspects of something", "This study guide provides a comprehensive overview of English grammar."),
        VocabWord("Compromise", "An agreement reached by making concessions", "In a healthy relationship, both people need to compromise sometimes."),
        VocabWord("Conceal", "To hide or keep something from sight", "He tried to conceal his disappointment with a smile."),
        VocabWord("Concede", "To admit that something is true after denying it", "He had to concede that his team made a tactical mistake."),
        VocabWord("Concise", "Giving a lot of information clearly and in few words", "Please write a concise summary of this large article."),
        VocabWord("Conclusive", "Proving that something is definitely true", "The DNA test provided conclusive proof of his identity."),
        VocabWord("Condone", "To accept or allow wrong behavior to continue", "We cannot condone any form of violence or bullying."),
        VocabWord("Conducive", "Making a certain outcome likely or possible", "A quiet environment is conducive to deep studying."),
        VocabWord("Confide", "To share a secret with someone you trust", "She decided to confide in her best friend about her worries."),
        VocabWord("Conform", "To comply with standard rules or laws", "All students must conform to the school dress code."),
        VocabWord("Confront", "To face and deal with a difficult situation directly", "You need to confront your fears to overcome them."),
        VocabWord("Conscientious", "Wishing to do one's work well and thoroughly", "She is a conscientious worker who never leaves a task incomplete."),
        VocabWord("Consecutive", "Following continuously in an unbroken order", "It rained heavily for three consecutive days."),
        VocabWord("Consequence", "A result or effect of an action", "You must be ready to face the consequences of your choice."),
        VocabWord("Conservative", "Preferring traditional values and resisting change", "My grandparents have a very conservative outlook on life."),
        VocabWord("Considerable", "Notably large in size, amount, or importance", "There has been a considerable increase in sales this month."),
        VocabWord("Consistent", "Always behaving or performing in the same good way", "To master English speaking, you need to be consistent."),
        VocabWord("Conspicuous", "Clearly visible or attracting a lot of notice", "The bright red car was very conspicuous parked on the street."),
        VocabWord("Constant", "Happening continuously over a long period", "The constant noise from the street made it hard to sleep."),
        VocabWord("Constitute", "To be the parts that form a whole", "Nine players constitute a standard baseball team."),
        VocabWord("Constraint", "A limitation or restriction that controls action", "Financial constraints forced him to delay his higher education."),
        VocabWord("Contemplate", "To think deeply or thoughtfully about something", "I need some time to contemplate my future career options."),
        VocabWord("Contemporary", "Belonging to or occurring in the present time; modern", "She loves listening to contemporary pop music."),
        VocabWord("Contradict", "To say the opposite of what someone else has said", "The new evidence completely contradicts his old statement."),
        VocabWord("Controversial", "Causing a lot of public disagreement and discussion", "The government passed a highly controversial law today."),
        VocabWord("Conventional", "Based on what is generally done or believed traditionally", "He prefers conventional farming methods over modern ones."),
        VocabWord("Convey", "To communicate a message, feeling, or idea clearly", "Please convey my best wishes to your family."),
        VocabWord("Convincing", "Capable of causing someone to believe something is true", "He gave a convincing reason for leaving the job early."),
        VocabWord("Cope", "To deal effectively with a difficult situation", "It can be hard to cope with high job stress daily."),
        VocabWord("Cordial", "Warm, polite, and friendly in manner", "We received a very cordial welcome at the party."),
        VocabWord("Correlation", "A mutual relationship or connection between two things", "There is a strong correlation between hard work and success."),
        VocabWord("Corroborate", "To confirm or give support to a statement or theory", "Two witnesses came ahead to corroborate his story."),
        // Batch 3 (D)
        VocabWord("Daunting", "Intimidating or discouraging; difficult", "Learning 1000 new advanced words can seem daunting at first."),
        VocabWord("Dearth", "A scarcity or lack of something", "There is a dearth of skilled web developers in the current market."),
        VocabWord("Debunk", "To expose the falseness of a myth or idea", "The laboratory experiment managed to debunk the old theory."),
        VocabWord("Decipher", "To succeed in understanding or reading something cryptic", "It took me hours to decipher his messy handwriting."),
        VocabWord("Decline", "To politely refuse / A continuous decrease", "She decided to decline the job offer due to the long commute."),
        VocabWord("Dedicate", "To devote time or effort to a specific purpose", "You must dedicate at least 30 minutes daily to practice speaking."),
        VocabWord("Defer", "To put off an action to a later time; postpone", "We had to defer our decision until we got the complete data."),
        VocabWord("Defiant", "Showing open resistance or disobedience", "The defiant child refused to eat his green vegetables."),
        VocabWord("Deficit", "The amount by which something is too small; shortage", "The country is facing a massive budget deficit this year."),
        VocabWord("Definite", "Clearly stated or decided; certain", "We need a definite answer by tomorrow morning to book the venue."),
        VocabWord("Deliberate", "Done consciously and intentionally", "Breaking the glass window was a deliberate act, not an accident."),
        VocabWord("Delicate", "Easily broken or damaged; fragile", "Please handle this antique vase carefully, it is very delicate."),
        VocabWord("Delineate", "To describe or portray something precisely", "The manager will delineate your exact daily responsibilities tomorrow."),
        VocabWord("Delusion", "A mistaken or false belief despite contrary evidence", "He is under the delusion that he can win without any practice."),
        VocabWord("Demeanor", "Outward behavior or bearing", "Her calm and professional demeanor impressed the interviewers."),
        VocabWord("Demolish", "To completely destroy a building or structure", "The city council decided to demolish the old, unsafe building."),
        VocabWord("Demonstrate", "To clearly show or explain how something works", "The trainer will demonstrate how to use the new software safely."),
        VocabWord("Denounce", "To publicly declare something to be wrong or evil", "The local leaders came together to denounce the violent incident."),
        VocabWord("Depict", "To represent or show something through art or words", "The movie tries to depict the daily struggles of a middle-class family."),
        VocabWord("Deplorable", "Deserving strong condemnation; shockingly bad", "The living conditions in the crowded slum area were deplorable."),
        VocabWord("Deposit", "To put money in a bank / To leave a layer of something", "I need to visit the bank to deposit this monthly check."),
        VocabWord("Depreciate", "To diminish or drop in value over time", "A brand new car will depreciate in value the moment you drive it off."),
        VocabWord("Deprive", "To prevent someone from having or using something", "You should never deprive your body of proper sleep and rest."),
        VocabWord("Derive", "To obtain something from a specific origin or source", "Many modern English words actually derive from ancient Latin."),
        VocabWord("Desolate", "Deserted of people and in a state of bleak emptiness", "The old railway station looked completely desolate after midnight."),
        VocabWord("Despair", "The complete loss or absence of hope", "He was in deep despair after losing his important documents."),
        VocabWord("Despise", "To feel deep hatred or disgust for something", "Honest people usually despise anyone who tells constant lies."),
        VocabWord("Detached", "Separate or disconnected / Emotionally distant", "He maintained a detached attitude throughout the argument."),
        VocabWord("Deter", "To discourage someone from doing something", "High security cameras are installed to deter thieves from stealing."),
        VocabWord("Deteriorate", "To become progressively worse over time", "If you don't store the milk in the fridge, its quality will deteriorate."),
        VocabWord("Detrimental", "Tending to cause harm; damaging", "Spending too much time on smartphones is detrimental to eye health."),
        VocabWord("Devastate", "To destroy or ruin something completely", "A severe earthquake can devastate an entire city within seconds."),
        VocabWord("Deviate", "To depart from an established course or plan", "Do not deviate from the main topic during the official presentation."),
        VocabWord("Devote", "To give most of one's time or resources to a cause", "She wants to devote her retirement years to social service."),
        VocabWord("Dexterity", "Skill in performing tasks, especially with the hands", "The surgeon showed great dexterity during the complex operation."),
        VocabWord("Diagnose", "To identify the nature of an illness or problem", "Doctors used advanced scans to diagnose the cause of his pain."),
        VocabWord("Dictate", "To state authoritatively / Say aloud words to be typed", "The CEO will dictate the new terms of the agreement to his secretary."),
        VocabWord("Differentiate", "To recognize or show the difference between things", "It is difficult to differentiate between the two identical twins."),
        VocabWord("Diffuse", "To spread or cause to spread over a wide area", "The pleasant aroma of incense sticks began to diffuse in the room."),
        VocabWord("Dignity", "The state of being worthy of honor or respect", "Always treat poor people with utmost dignity and kindness."),
        VocabWord("Diligent", "Showing care and continuous effort in one's work", "A diligent student always completes his assignments on time."),
        VocabWord("Diminish", "To make or become less in size or importance", "The pain will gradually diminish after taking this medicine."),
        VocabWord("Diplomatic", "Tactful and sensitive in dealing with people", "You need a diplomatic approach to resolve this internal office fight."),
        VocabWord("Dire", "Extremely serious, urgent, or terrible", "The farmers are in dire need of water due to the long drought."),
        VocabWord("Discern", "To perceive, recognize, or notice something clearly", "It was hard to discern the shape of the ship through the thick fog."),
        VocabWord("Discipline", "The practice of training people to obey rules", "Maintaining strict discipline is necessary for success in life."),
        VocabWord("Disclose", "To make secret or private information known", "The company promised not to disclose your personal phone number."),
        VocabWord("Discrepancy", "A lack of compatibility or similarity between two facts", "There is a major discrepancy between his two statements."),
        VocabWord("Disdain", "The feeling that someone or something is unworthy of respect", "She looked at the cheap plastic toy with obvious disdain."),
        VocabWord("Dismay", "Distress or disappointment caused by something unexpected", "To our utter dismay, the famous museum was closed for repairs."),
        // Batch 4 & 5 (D-F)
        VocabWord("Dismiss", "To reject or put away an idea/person", "The manager decided to dismiss the silly rumor immediately."),
        VocabWord("Disparate", "Essentially different in kind; entirely unlike", "The two countries have disparate cultures and traditions."),
        VocabWord("Dispel", "To make a doubt or feeling disappear", "Her kind words helped to dispel my fears about the interview."),
        VocabWord("Disrupt", "To interrupt an event or activity by causing a disturbance", "Heavy rainfall can disrupt the local train services."),
        VocabWord("Distort", "To twist out of shape or misrepresent the truth", "Do not try to distort the facts to save yourself."),
        VocabWord("Diversify", "To add variety or expand into new areas", "It is wise to diversify your investments across different sectors."),
        VocabWord("Divert", "To change the direction of something", "The police had to divert traffic due to an accident ahead."),
        VocabWord("Docile", "Quiet, easy to influence, or manage", "The street dog became very docile after getting some food."),
        VocabWord("Dominant", "Most important, powerful, or influential", "English is a dominant language in international business."),
        VocabWord("Drastic", "Likely to have a strong or far-reaching effect", "The company had to take drastic steps to cut down costs."),
        VocabWord("Durable", "Able to withstand wear, pressure, or damage", "These leather boots are highly durable and long-lasting."),
        VocabWord("Dwell", "To live or stay in a particular place", "Many tribal communities still dwell deep inside the forest."),
        VocabWord("Dwindle", "To gradually diminish in size, amount, or strength", "Our water supply started to dwindle during the hot summer."),
        VocabWord("Dynamic", "Constant change, activity, or progress; energetic", "The tech industry requires a dynamic approach to survive."),
        VocabWord("Earnest", "Resulting from or showing sincere conviction", "He made an earnest request for financial assistance."),
        VocabWord("Eccentric", "Unconventional and slightly strange behavior", "The old scientist was known for his eccentric habits."),
        VocabWord("Economical", "Giving good value in relation to the money spent", "Buying a monthly bus pass is very economical for students."),
        VocabWord("Edible", "Safe or fit to be eaten", "Make sure the wild mushrooms are edible before cooking them."),
        VocabWord("Effective", "Successful in producing a desired result", "This new strategy proved to be highly effective for sales."),
        VocabWord("Efficient", "Working in a well-organized and competent way", "An efficient engine consumes less fuel and gives more mileage."),
        VocabWord("Elaborate", "Involving many carefully arranged parts; detailed", "They made elaborate arrangements for the wedding function."),
        VocabWord("Elated", "Ecstatically happy or proud", "She was elated when she received the acceptance letter."),
        VocabWord("Elegant", "Graceful and stylish in appearance or manner", "The actress wore an elegant traditional dress at the event."),
        VocabWord("Elevate", "To raise or lift to a higher position", "Regular reading can elevate your knowledge and vocabulary."),
        VocabWord("Eligible", "Having the right to do or obtain something", "You must over 18 to be eligible to vote in elections."),
        VocabWord("Eliminate", "To completely remove or get rid of something", "Try to eliminate junk food from your daily diet."),
        VocabWord("Eloquent", "Fluent or persuasive in speaking or writing", "The Prime Minister gave an eloquent speech at the assembly."),
        VocabWord("Elusive", "Difficult to find, catch, or achieve", "The true meaning of happiness remains elusive to many."),
        VocabWord("Embark", "To go on board a ship or begin a new journey", "The young graduate is ready to embark on his new career."),
        VocabWord("Empathy", "The ability to understand and share feelings of another", "A doctor must show empathy toward suffering patients."),
        VocabWord("Emphasize", "To give special importance or value to something", "Teachers always emphasize the value of regular revision."),
        VocabWord("Empirical", "Based on observation or experience rather than theory", "Scientists need empirical evidence to prove their hypothesis."),
        VocabWord("Emulate", "To match or surpass a person, typically by imitation", "Young cricketers always try to emulate Sachin Tendulkar."),
        VocabWord("Encounter", "To unexpectedly experience or face something", "You might encounter some difficulties in the initial days."),
        VocabWord("Endeavor", "An earnest attempt to achieve a goal", "We wish you the best of luck in your future endeavors."),
        VocabWord("Endorse", "To declare one's public approval or support of", "Famous celebrities often endorse popular luxury brands."),
        VocabWord("Endure", "To suffer patiently; to tolerate or last long", "A mother can endure any pain for the sake of her child."),
        VocabWord("Enforce", "To compel observance of a law or rule", "The police are here to enforce traffic rules strictly."),
        VocabWord("Enhance", "To intensify, increase, or further improve the quality", "Adding fresh herbs will enhance the flavor of the soup."),
        VocabWord("Enigma", "A person or thing that is mysterious or difficult to understand", "The cause of the ancient plane crash remains an enigma."),
        VocabWord("Enormous", "Very large in size, quantity, or extent", "The new stadium has an enormous seating capacity."),
        VocabWord("Ensure", "To make certain that something will occur", "Please ensure that all doors are locked before leaving."),
        VocabWord("Entail", "To involve something as a necessary consequence", "Starting a new business will entail a lot of hard work."),
        VocabWord("Enterprise", "A project or undertaking, typically a bold one; a business", "Setting up a global enterprise requires vast resources."),
        VocabWord("Enthusiastic", "Showing intense and eager enjoyment or interest", "The children were highly enthusiastic about the picnic tour."),
        VocabWord("Entitle", "To give a right to a benefit or privilege", "This coupon will entitle you to a free dessert."),
        VocabWord("Envision", "To imagine as a future possibility", "I envision a world where clean energy is free for everyone."),
        VocabWord("Epitome", "A perfect example of a particular quality or type", "Mother Teresa was the epitome of kindness and charity."),
        VocabWord("Eradicate", "To completely destroy or put an end to something", "The government aims to eradicate poverty from the nation."),
        VocabWord("Erroneous", "Wrong, incorrect, or based on a mistake", "The report contained erroneous information about the data."),
        VocabWord("Escalate", "To increase rapidly or become more intense", "A small argument can escalate into a major fight quickly."),
        VocabWord("Essence", "The intrinsic nature or indispensable quality of something", "Trust is the true essence of any beautiful relationship."),
        VocabWord("Essential", "Absolutely necessary; extremely important", "Fresh water and clean air are essential for survival."),
        VocabWord("Establish", "To set up an organization, system, or set of rules", "The school was established in the year 1995."),
        VocabWord("Esteem", "Respect and admiration, typically for a person", "He is held in high esteem by all his colleagues."),
        VocabWord("Estimate", "To roughly calculate or judge the value or quantity", "Can you give me a rough estimate of the repair cost?"),
        VocabWord("Eternal", "Lasting or existing forever; without end", "True love and friendship are often considered eternal."),
        VocabWord("Ethical", "Relating to moral principles; right and fair", "It is not ethical to copy someone else's hard work."),
        VocabWord("Euphoria", "A feeling or state of intense excitement and happiness", "Winning the championship created a state of euphoria."),
        VocabWord("Evade", "To escape or avoid something, especially by trickery", "The thief managed to evade the police for three weeks."),
        VocabWord("Evaluate", "To assess or judge the value or quality of something", "The teachers will evaluate your performance next week."),
        VocabWord("Evident", "Plain or obvious; clearly seen or understood", "It was evident from his face that he was very disappointed."),
        VocabWord("Evoke", "To bring or recall a feeling or memory to the conscious mind", "Old school photographs always evoke beautiful memories."),
        VocabWord("Evolve", "To develop gradually, especially from a simple to complex form", "Smart devices continue to evolve with advanced technology."),
        VocabWord("Exaggerate", "To represent something as being larger or better than it is", "Don't exaggerate the problem, it is a very minor issue."),
        VocabWord("Exasperate", "To irritate or frustrate someone intensely", "His constant silly questions began to exasperate the boss."),
        VocabWord("Excel", "To be exceptionally good at or proficient in an activity", "Hard-working students usually excel in their academics."),
        VocabWord("Exceptional", "Unusually good; outstanding or extraordinary", "The young boy possesses exceptional talent in mathematics."),
        VocabWord("Exclude", "To deny someone or something access; keep out", "The price of the package will exclude dinner charges."),
        VocabWord("Exemplary", "Serving as a desirable model; representing the best", "The officer was praised for his exemplary courage."),
        VocabWord("Exempt", "Free from an obligation or liability imposed on others", "Senior citizens are often exempt from paying certain taxes."),
        VocabWord("Exert", "To apply continuous physical or mental effort", "Do not exert too much pressure on your injured leg."),
        VocabWord("Exhaustive", "Fully comprehensive and thorough; leaving nothing out", "The police conducted an exhaustive search of the building."),
        VocabWord("Exotic", "Originating in or characteristic of a distant foreign country", "We saw several species of exotic birds at the sanctuary."),
        VocabWord("Expand", "To become larger in size, volume, or scope", "The retail company plans to expand its business nationwide."),
        VocabWord("Expedite", "To make an action or process happen sooner or faster", "Please expedite the delivery process, it is an urgent order."),
        VocabWord("Expertise", "Expert skill or knowledge in a particular field", "She has deep expertise in managing financial accounts."),
        VocabWord("Explicit", "Stated clearly and in detail, leaving no room for confusion", "The manual gives explicit instructions on how to assemble it."),
        VocabWord("Exploit", "To make full use of and derive benefit from a resource", "We must learn to exploit renewable resources like solar energy."),
        VocabWord("Explore", "To travel through an unfamiliar area to learn about it", "I love to explore new historical places during my holidays."),
        VocabWord("Exquisite", "Extremely beautiful and delicate", "The museum displayed an exquisite collection of diamonds."),
        VocabWord("Extensive", "Covering or affecting a large area; widespread", "The storm caused extensive damage to the coastal areas."),
        VocabWord("Extinguish", "To cause a fire to cease burning", "Firefighters took three hours to extinguish the massive fire."),
        VocabWord("Extol", "To praise enthusiastically", "The principal likes to extol the virtues of discipline."),
        VocabWord("Extract", "To remove or take out something by effort or force", "The dentist had to extract a decayed tooth yesterday."),
        VocabWord("Extraordinary", "Very unusual or remarkable; remarkable", "The movie achieved extraordinary success worldwide."),
        VocabWord("Extravagant", "Lacking restraint in spending money or using resources", "Spending thousands on a single shirt is very extravagant."),
        VocabWord("Fabricate", "To invent or concoct something, typically with deceitful intent", "Do not try to fabricate a fake story to skip the class."),
        VocabWord("Facilitate", "To make an action or process easier", "Modern apps help to facilitate instant online payments."),
        VocabWord("Fallacy", "A mistaken belief, especially one based on unsound argument", "The idea that money buys absolute happiness is a fallacy."),
        VocabWord("Falter", "To lose strength or momentum; speak hesitantly", "Her voice began to falter as she spoke about her struggles."),
        VocabWord("Fascinating", "Extremely interesting or charming", "The documentary gave a fascinating insight into space life."),
        VocabWord("Fatal", "Causing death; leading to failure or disaster", "Driving without a seatbelt can lead to a fatal accident."),
        VocabWord("Fathom", "To understand a difficult problem after much thought", "It is hard to fathom why he made such a sudden decision."),
        VocabWord("Feasible", "Possible to do easily or conveniently", "Implementing this new plan seems completely feasible now."),
        VocabWord("Feeble", "Lacking physical strength, especially as a result of age or illness", "The old man gave a feeble smile from his hospital bed."),
        VocabWord("Ferocious", "Savagely fierce, cruel, or violent", "A ferocious tiger was spotted near the village borders."),
        VocabWord("Fervent", "Having or displaying a passionate intensity", "She is a fervent supporter of environmental protection laws."),
        VocabWord("Fickle", "Changing frequently, especially as regards one's loyalties", "Stock markets are known to be highly fickle and risky."),
        VocabWord("Fictitious", "Not real or true, being imaginary or fabricated", "All characters in this television show are purely fictitious."),
        // Batch 6 & 7 (F-I)
        VocabWord("Flamboyant", "Noticeably vibrant, stylish, or showy", "The musician is known for his flamboyant costumes on stage."),
        VocabWord("Flawless", "Without any imperfections or defects; perfect", "Her performance in the classical dance was completely flawless."),
        VocabWord("Fleeting", "Lasting for a very short time", "We caught a fleeting glimpse of the shooting star before it disappeared."),
        VocabWord("Flourish", "To grow or develop vigorously; thrive", "Plants flourish when given the right amount of sunlight and water."),
        VocabWord("Fluctuate", "To rise and fall irregularly in number or amount", "Fuel prices continue to fluctuate every week based on market demand."),
        VocabWord("Formidable", "Inspiring fear or respect through being large or powerful", "The champion boxer faces a formidable opponent in the final match."),
        VocabWord("Fortitude", "Courage in pain or adversity; mental strength", "She showed great mental fortitude while fighting her long illness."),
        VocabWord("Foster", "To encourage or promote the development of something", "The teacher tried to foster a love for reading among her young students."),
        VocabWord("Frivolous", "Not having any serious purpose or value", "Try to avoid spending money on frivolous luxury items."),
        VocabWord("Frugal", "Simple, sparing, and economical regarding food or money", "He leads a very frugal lifestyle and saves most of his income."),
        VocabWord("Futile", "Incapable of producing any useful result; pointless", "It is futile to argue with someone who refuses to listen to facts."),
        VocabWord("Gallant", "Brave, heroic, or giving special attention to others", "The gallant soldier was awarded a medal for saving citizens from fire."),
        VocabWord("Gauge", "To estimate or measure the magnitude or amount", "It is difficult to gauge the success of the new project so early."),
        VocabWord("Genial", "Friendly, cheerful, and warm in manner", "Our new manager is extremely genial and easy to talk to."),
        VocabWord("Ghastly", "Causing great horror or fear; frightful", "The news reported a ghastly road accident on the highway last night."),
        VocabWord("Gigantic", "Of very great size or extent; huge", "The company moved its operations into a gigantic new corporate office."),
        VocabWord("Glimmer", "A faint, wavering light / A slight sign of something", "There is still a glimmer of hope that the missing explorers will return."),
        VocabWord("Gloomy", "Dark or poorly lit / Feeling distressed or pessimistic", "The cloudy weather made the entire afternoon look very gloomy."),
        VocabWord("Grandeur", "Splendor and impressiveness, especially of appearance", "Visitors are always amazed by the grandeur of the ancient royal palace."),
        VocabWord("Gratify", "To give pleasure or satisfaction to someone", "The team worked hard to gratify the high expectations of their clients."),
        VocabWord("Grievance", "A real or imagined wrong causing ground for complaint", "Employees can submit their official grievances to the HR department."),
        VocabWord("Grim", "Very serious, gloomy, or depressing in appearance", "The economic future of the small company looks quite grim."),
        VocabWord("Grotesque", "Comically or repulsively ugly or distorted", "The horror movie featured a grotesque monster living under the bridge."),
        VocabWord("Grudge", "A persistent feeling of ill will or resentment", "It is better to forgive people rather than holding a long grudge."),
        VocabWord("Gullible", "Easily persuaded to believe something; naive", "He is so gullible that he believes everything he reads on social media."),
        VocabWord("Haggard", "Looking exhausted and unwell, especially from fatigue", "His face looked haggard after working continuously for 24 hours."),
        VocabWord("Hamper", "To hinder or impede the movement or progress of", "Severe water logging began to hamper the rescue operations in the city."),
        VocabWord("Haphazard", "Lacking any obvious principle of organization; random", "The books were stacked in a haphazard manner across the study room floor."),
        VocabWord("Harangue", "A lengthy and aggressive speech or lecture", "The angry customer gave a long harangue to the store manager."),
        VocabWord("Harbor", "To keep a thought or feeling in one's mind secretly", "You should not harbor negative feelings toward your old friends."),
        VocabWord("Hardship", "Severe suffering or privation", "The poor family faced great hardship during the severe winter months."),
        VocabWord("Harmonious", "Tuneful; balanced, friendly, and peaceful", "The team worked in a harmonious way to complete the complex task."),
        VocabWord("Haughty", "Arrogantly superior and disdainful", "The rich man's haughty attitude made him very unpopular in the locality."),
        VocabWord("Havoc", "Widespread destruction or great confusion", "The sudden software glitch created total havoc at the airport."),
        VocabWord("Hazardous", "Risky, dangerous, or unsafe", "Workers must wear safety masks while handling hazardous chemicals."),
        VocabWord("Heed", "To pay close attention to advice or warning", "You must heed the warning signs displayed near the deep sea beach."),
        VocabWord("Heinous", "Extremely wicked, deeply criminal, or hateful", "The court gave strict punishment to the criminal for his heinous crime."),
        VocabWord("Hinder", "To create difficulties for someone, resulting in delay", "High noise levels can hinder your ability to focus on deep studying."),
        VocabWord("Hindrance", "A thing that provides resistance, delay, or obstruction", "Lack of stable internet access proved to be a major hindrance for online classes."),
        VocabWord("Hoard", "To collect and hide away valued objects or goods", "Some shopkeepers try to hoard essential goods to sell them at high prices later."),
        VocabWord("Hoax", "A humorous or malicious deception; a practical joke", "The bomb threat at the shopping mall turned out to be a complete hoax."),
        VocabWord("Holistic", "Dealing with or treating the whole of something", "A holistic approach to health includes proper diet, exercise, and sleep."),
        VocabWord("Homage", "Special honor or respect shown publicly", "Leaders gathered at the memorial to pay homage to the brave soldiers."),
        VocabWord("Hostile", "Showing strong dislike; unfriendly or antagonistic", "The local villagers were quite hostile toward the new factory project."),
        VocabWord("Humiliate", "To make someone feel ashamed or foolish publicly", "You should never humiliate anyone in front of their colleagues."),
        VocabWord("Humility", "The quality of having a modest or low view of one's importance", "Despite winning three global awards, the artist maintains deep humility."),
        VocabWord("Hypocrisy", "Claiming to have higher standards than one actually practices", "It is pure hypocrisy to advise others to save water while wasting it yourself."),
        VocabWord("Hypothesis", "A proposed explanation made on the basis of limited evidence", "The researchers formulated a new hypothesis to explain the sudden weather change."),
        VocabWord("Ignite", "To catch fire or cause something to burn", "A small spark from the open electric wire managed to ignite the dry grass."),
        VocabWord("Illegible", "Not clear enough to be read; unreadable", "The doctor wrote the prescription in an illegible handwriting."),
        VocabWord("Illuminate", "To light up or make something clear and bright", "Bright street lamps were installed to illuminate the dark alleyways."),
        VocabWord("Illustrious", "Well known, respected, and admired for past achievements", "The university is proud of its illustrious history of producing great scientists."),
        VocabWord("Immaculate", "Perfect clean, neat, or tidy; spotless", "She always keeps her white formal uniform in an immaculate condition."),
        VocabWord("Imminent", "About to happen very soon; fast approaching", "Black clouds in the sky indicate that a heavy downpour is imminent."),
        VocabWord("Immune", "Protected or exempt from a disease or effects", "Regular vaccinations help to make children immune to dangerous viruses."),
        VocabWord("Impartial", "Treating all rivals or disputants equally; fair", "A referee must remain completely impartial during a football match."),
        VocabWord("Impassioned", "Filled with or showing great emotion or passion", "The activist made an impassioned plea to protect old forest areas."),
        VocabWord("Impeccable", "In accordance with the highest standards; faultless", "The luxury hotel is famous across the country for its impeccable service."),
        VocabWord("Impede", "To delay or prevent someone or something by obstructing them", "High traffic jams will impede our progress to reach the wedding venue on time."),
        VocabWord("Imperative", "Of vital importance; crucial or mandatory", "It is imperative to submit your verified legal documents by Friday evening."),
        VocabWord("Imperceptible", "So slight, gradual, or subtle as not to be perceived", "The growth of the indoor plant was almost imperceptible on a daily basis."),
        VocabWord("Impetuous", "Acting or done quickly and without thought or care", "Making an impetuous decision to quit your current job is highly risky."),
        VocabWord("Implement", "To put a decision, plan, or agreement into effect", "The school management decided to implement new strict safety rules."),
        VocabWord("Implicate", "To show someone to be involved in a crime", "The police found fresh evidence that might implicate him in the theft."),
        VocabWord("Implicit", "Implied though not plainly expressed; absolute", "The children have implicit trust in their parents' choices."),
        VocabWord("Implore", "To beg someone earnestly or desperately to do something", "I implore you to think twice before making such a major investment."),
        VocabWord("Imply", "To strongly suggest the truth of something without stating it directly", "Her silent response seemed to imply that she agreed with our new plan."),
        VocabWord("Impoverished", "Made poor; lacking modern resources or funds", "The NGO is working hard to build smart schools in impoverished villages."),
        VocabWord("Impregnable", "Unable to be captured, broken into, or defeated", "The ancient fort built on top of the steep hill was completely impregnable."),
        VocabWord("Impromptu", "Done without being planned, organized, or rehearsed", "He gave an impromptu speech at the party when requested by the host."),
        VocabWord("Improvise", "To create or perform something spontaneously without preparation", "When the microphone stopped working, the actor had to improvise his dialogue."),
        VocabWord("Imprudent", "Not showing care for the consequences of an action; unwise", "It is highly imprudent to drive a fast car on wet roads during heavy rain."),
        VocabWord("Impudent", "Not showing due respect for another person; impertinent", "The student faced strict action for making an impudent remark to the teacher."),
        VocabWord("Impulse", "A sudden strong and unreflective urge or desire to act", "She bought the expensive leather handbag on an impulse without checking price."),
        VocabWord("Inadvertent", "Not resulting from deliberate planning; accidental", "The system breakdown was an inadvertent mistake caused during server updates."),
        VocabWord("Inane", "Lacking sense or meaning; silly or stupid", "Stop wasting our important meeting time by asking inane questions."),
        VocabWord("Inarticulate", "Unable to express one's ideas or feelings clearly", "He became completely inarticulate due to extreme nervousness during the interview."),
        VocabWord("Inaugurate", "To open a building officially; begin a system", "The chief guest will arrive at 10 AM to inaugurate the new science hospital."),
        VocabWord("Incandescent", "Emitting light as a result of being heated / Extremely bright", "The old electric bulbs produce light using a glowing incandescent filament."),
        VocabWord("Incense", "To make someone extraordinarily angry", "His constant lazy attitude managed to incense his business partners deeply."),
        VocabWord("Incentive", "A thing that motivates or encourages one to do something", "The firm offers a monthly cash incentive to the top performing salespeople."),
        VocabWord("Incessant", "Continuing without pause or interruption", "The incessant barking of the neighbor's dog kept me awake all night long."),
        VocabWord("Incidental", "Happening as a minor accompaniment to something else", "You should be ready to pay for minor incidental costs during your travel."),
        VocabWord("Incisive", "Intelligently analytical and clear-thinking; sharp", "Her incisive analysis of the market helped the company avoid a huge loss."),
        VocabWord("Incite", "To encourage or stir up violent or unlawful behavior", "Lending support to fake social media posts can incite public anger quickly."),
        VocabWord("Inclination", "A person's natural tendency or urge to act or feel in a way", "I have a strong inclination to study art history rather than pursuing science engineering."),
        VocabWord("Inclusive", "Including all the services or items normally expected; comprehensive", "The vacation tour price is fully inclusive of hotel stay and three meals daily."),
        VocabWord("Incognito", "Having one's true identity concealed; in disguise", "The famous Hollywood celebrity traveled across the country completely incognito."),
        VocabWord("Incoherent", "Expressed in an incomprehensible or confusing way; unclear", "He was murmuring some incoherent sentences in his deep sleep last night."),
        VocabWord("Incompatible", "So opposed in character as to be incapable of existing together", "The old operating software is completely incompatible with this new smartphone model."),
        VocabWord("Incompetent", "Not having or showing the necessary skills to do something", "The company decided to terminate the lazy and incompetent contractor immediately."),
        VocabWord("Inconceivable", "Not capable of being imagined or grasped mentally; unbelievable", "A few decades ago, video calling across continents was considered inconceivable."),
        VocabWord("Incongruous", "Not in harmony or keeping with the surroundings; out of place", "Wearing bright sports shoes with a formal heavy tuxedo looked highly incongruous."),
        VocabWord("Inconsequential", "Not important or significant; minor", "Don't waste your energy worrying about small, inconsequential details."),
        VocabWord("Incontrovertible", "Not able to be denied or disputed; absolute truth", "The high-definition security footage provided incontrovertible proof of the robbery."),
        VocabWord("Incorporate", "To take in or include something as a part of a whole", "You should try to incorporate fresh green vegetables into your standard daily diet."),
        VocabWord("Incredulous", "Unwilling or unable to believe something; skeptical", "She gave an incredulous laugh when he claimed he could jump over the tall wall."),
        VocabWord("Increment", "An increase or addition, especially one of a series", "The company announced a 10% salary increment for all employees this July."),
        VocabWord("Incumbent", "Necessary for someone as a duty or responsibility", "It is incumbent upon the citizens to keep their local parks and streets clean."),
        VocabWord("Incur", "To become subject to something unwelcome as a result of behavior", "If you do not pay your monthly credit bill on time, you will incur a heavy fine.")
    )
}
