package com.smnm.englishtrackingai

object BeginnerWords {
    val list = listOf(
        VocabWord("Accept", "To say yes to something", "I accept your apology."),
        VocabWord("Allow", "To give permission", "Please allow me to go inside."),
        VocabWord("Bargain", "To ask for a lower price", "She knows how to bargain with shopkeepers."),
        VocabWord("Believe", "To feel sure that something is true", "I believe you are telling the truth."),
        VocabWord("Borrow", "To take something for a short time", "Can I borrow your umbrella for today?"),
        VocabWord("Choose", "To pick out from many options", "You can choose any dress you like."),
        VocabWord("Comfortable", "Providing physical ease or relaxation", "This chair is very comfortable to work."),
        VocabWord("Compare", "To look at similarities or differences", "Don't compare your life with others."),
        VocabWord("Complain", "To say you are not happy with something", "The customers complain about the slow service."),
        VocabWord("Curious", "Wanting to know or learn more", "The child is very curious about nature."),
        VocabWord("Decide", "To make a final choice", "You need to decide your goal quickly."),
        VocabWord("Delay", "To make something late", "The flight was delayed by two hours."),
        VocabWord("Describe", "To explain how something looks or is", "Can you describe the road to the station?"),
        VocabWord("Disappear", "To go out of sight suddenly", "The thief disappeared into the crowd."),
        VocabWord("Encourage", "To give support or confidence", "Teachers always encourage students to speak."),
        VocabWord("Essential", "Absolutely necessary or very important", "Good sleep is essential for a sharp mind."),
        VocabWord("Expect", "To think that something will happen", "I did not expect such a beautiful gift."),
        VocabWord("Explain", "To make something easy to understand", "Please explain this English topic again."),
        VocabWord("Familiar", "Well-known or easily recognized", "Your voice sounds very familiar to me."),
        VocabWord("Forget", "To fail to remember something", "Don't forget to lock the door."),
        VocabWord("Frequently", "Happening often or many times", "He frequently checks his smartphone."),
        VocabWord("Gather", "To come together in one place", "People gathered to watch the street show."),
        VocabWord("Grateful", "Feeling or showing thanks", "I am deeply grateful for your timely help."),
        VocabWord("Healthy", "In good physical condition", "Eating fruits keeps your body healthy."),
        VocabWord("Hesitate", "To pause because of doubt or fear", "Never hesitate to speak English, even if wrong."),
        VocabWord("Ignore", "To pay no attention to someone", "Just ignore the negative people around you."),
        VocabWord("Imagine", "To form a picture in the mind", "Can you imagine a life without the internet?"),
        VocabWord("Immediate", "Done right now without any delay", "This problem needs your immediate attention."),
        VocabWord("Improve", "To make or become better", "Daily practice will improve your fluency."),
        VocabWord("Include", "To add as a part of something", "Does the ticket price include lunch?"),
        VocabWord("Inform", "To give information or tell someone", "Please inform the team about the timing."),
        VocabWord("Journey", "An act of traveling from one place to another", "Have a safe and happy journey ahead!"),
        VocabWord("Lend", "To give something for a short time", "Will you lend me your laptop for an hour?"),
        VocabWord("Maintain", "To keep something in good condition", "It is important to maintain a clean house."),
        VocabWord("Manage", "To handle or control a situation", "Don't worry, I can manage this setup alone."),
        VocabWord("Mistake", "Something done wrong by accident", "It's okay, everyone makes a mistake sometimes."),
        VocabWord("Necessary", "Needed to be done / Urgent", "It is necessary to wear a helmet while riding."),
        VocabWord("Notice", "To see or become aware of something", "Did you notice the new signboards on the road?"),
        VocabWord("Opportunity", "A good chance to do something", "This new job is a brilliant opportunity for you."),
        VocabWord("Prepare", "To get ready for something", "Give yourself enough time to prepare for tests."),
        VocabWord("Prevent", "To stop something from happening", "Washing hands helps to prevent diseases."),
        VocabWord("Promise", "To say surely that you will do something", "If you make a promise, you must keep it."),
        VocabWord("Provide", "To give what is needed to someone", "The government will provide free textbooks."),
        VocabWord("Receive", "To get or accept something sent", "Did you receive the confirmation message?"),
        VocabWord("Refuse", "To say no to an offer or request", "I had to refuse the offer because of time."),
        VocabWord("Remind", "To make someone remember something", "Please remind me to call him at 5 PM."),
        VocabWord("Require", "To need something for a purpose", "Plants require sunlight and water to grow."),
        VocabWord("Satisfied", "Feeling happy with what you got", "I am completely satisfied with my test results."),
        VocabWord("Suggest", "To give an idea or plan for consideration", "Can you suggest a good book for beginners?"),
        VocabWord("Support", "To help or hold up someone", "My family always supports my decisions."),
        VocabWord("Trust", "To believe someone is honest and good", "Relationships work better when you trust each other."),
        VocabWord("Understand", "To know the meaning of something", "Do you understand what the teacher said?"),
        VocabWord("Worry", "To feel anxious or nervous about problems", "Don't worry about the results, just do your best."),
        VocabWord("Advice", "An opinion about what someone should do", "She gave me good advice about my career."),
        VocabWord("Agree", "To have the same opinion as someone else", "I completely agree with your plan."),
        VocabWord("Amount", "How much of something there is", "Please pay the total amount at the counter."),
        VocabWord("Angry", "Feeling or showing strong displeasure", "Why are you getting angry over a small thing?"),
        VocabWord("Announce", "To make something known publicly", "The company will announce the winners tomorrow."),
        VocabWord("Anxious", "Feeling worried or nervous", "I feel anxious before speaking in public."),
        VocabWord("Apologize", "To say sorry for a mistake", "You must apologize for arriving late."),
        VocabWord("Argue", "To fight or disagree using words", "Don't argue with your friends over small things."),
        VocabWord("Arrange", "To plan or organize something neatly", "Can you arrange these books on the shelf?"),
        VocabWord("Arrive", "To reach a place at the end of a journey", "What time does the train arrive at the station?"),
        VocabWord("Assist", "To help someone with a task", "The shop staff is here to assist you."),
        VocabWord("Attend", "To go to or be present at an event", "I need to attend an important meeting tomorrow."),
        VocabWord("Average", "Standard, normal, or middle level", "His performance in school is average but good."),
        VocabWord("Avoid", "To stay away from someone or something", "Try to avoid using your phone while driving."),
        VocabWord("Balance", "An even distribution of weight or parts", "Try to keep a balance between work and health."),
        VocabWord("Beautiful", "Very pleasing to look at", "The view from the mountain top is beautiful."),
        VocabWord("Benefit", "An advantage or profit gained", "Regular exercise has many health benefits."),
        VocabWord("Blame", "To say someone is responsible for a bad thing", "Do not blame others for your own mistakes."),
        VocabWord("Boring", "Not interesting or exciting", "The movie was so boring that I fell asleep."),
        VocabWord("Brave", "Showing no fear in dangerous situations", "The brave boy saved the dog from the river."),
        VocabWord("Bright", "Filled with light or shining strongly", "The sun is very bright today, wear sunglasses."),
        VocabWord("Busy", "Having a lot of things to do", "I am a bit busy right now, can I call you later?"),
        VocabWord("Calm", "Peaceful, quiet, and not worried", "Please stay calm during an emergency situation."),
        VocabWord("Cancel", "To decide that an event will not happen", "They had to cancel the match due to heavy rain."),
        VocabWord("Careful", "Trying hard to avoid mistakes or danger", "Be careful while crossing the busy road."),
        VocabWord("Celebrate", "To enjoy a special event with fun", "We will celebrate my brother's birthday tonight."),
        VocabWord("Certain", "Completely sure about something", "Are you certain about the project deadline?"),
        VocabWord("Challenge", "A difficult task that tests your ability", "Learning a new language is a great challenge."),
        VocabWord("Change", "To make or become different", "You need to change your bad habits to grow."),
        VocabWord("Cheap", "Low in price or costing little money", "This local market sells very cheap clothes."),
        VocabWord("Clean", "Free from dirt, marks, or stains", "Always keep your study room neat and clean."),
        VocabWord("Clear", "Easy to see, hear, or understand", "Your explanation about the topic was very clear."),
        VocabWord("Clever", "Quick to learn and understand things", "He is a clever boy who solves puzzles fast."),
        VocabWord("Collect", "To bring things together from different places", "Children love to collect unique and colorful stones."),
        VocabWord("Common", "Happening often or found everywhere", "Cold and cough are very common in winter."),
        VocabWord("Complicated", "Hard to understand or solve", "This math problem is too complicated for me."),
        VocabWord("Confused", "Unable to think clearly or understand", "I am confused between choosing these two shirts."),
        VocabWord("Connect", "To join two or more things together", "You can connect your phone to the speaker via Bluetooth."),
        VocabWord("Continue", "To keep doing something without stopping", "Please continue reading the next page."),
        VocabWord("Control", "To order, limit, or rule something", "It is very important to control your anger."),
        VocabWord("Correct", "Free from mistakes; right or true", "Your answer to the last question is absolutely correct."),
        VocabWord("Create", "To make something new or original", "Chefs use different ingredients to create new dishes."),
        VocabWord("Crowd", "A large group of people in one place", "There was a huge crowd at the shopping mall."),
        VocabWord("Cruel", "Intentionally causing pain or suffering", "Being cruel to animals is a punishable offense."),
        VocabWord("Daily", "Happening or done every single day", "Reading news articles is a good daily habit."),
        VocabWord("Danger", "The possibility of harm, injury, or loss", "Going near the wild animals is full of danger."),
        VocabWord("Defend", "To protect someone or something from attack", "The soldiers fought hard to defend their country."),
        VocabWord("Delicious", "Having a very pleasant taste", "The food served at this restaurant is delicious."),
        VocabWord("Depend", "To rely on someone or something for help", "Children depend on their parents for everything."),
        VocabWord("Destroy", "To damage something so badly it cannot be used", "The fire destroyed the old wooden house completely."),
        VocabWord("Difference", "A way in which people or things are not the same", "What is the difference between these two phones?"),
        VocabWord("Difficult", "Hard to do, understand, or deal with", "Learning to ride a bicycle can be difficult at first."),
        VocabWord("Direct", "Going straight without stopping or changing direction", "Is there a direct flight from Delhi to Mumbai?"),
        VocabWord("Discover", "To find something new for the first time", "Scientists want to discover life on other planets."),
        VocabWord("Discuss", "To talk about something with someone", "We need to discuss our weekend holiday plan."),
        VocabWord("Dislike", "To not like someone or something", "I dislike waking up early on Sundays."),
        VocabWord("Divide", "To separate into two or more parts", "Please divide the cake equally among the children."),
        VocabWord("Doubt", "A feeling of not being sure about something", "If you have any doubt, you can ask me freely."),
        VocabWord("Drop", "To let something fall down by accident", "Be careful, do not drop the glass bowl."),
        VocabWord("Duty", "Something you must do because it is right or your job", "It is our duty to keep our city clean."),
        VocabWord("Early", "Happening before the usual or expected time", "I always wake up early in the morning."),
        VocabWord("Earn", "To get money by working", "He works hard to earn a good salary."),
        VocabWord("Easy", "Not difficult; simple to do", "The English test today was very easy."),
        VocabWord("Educate", "To teach or give knowledge to someone", "We must educate every child in the country."),
        VocabWord("Effect", "A change or result caused by something", "The medicine had a quick effect on his pain."),
        VocabWord("Effort", "Physical or mental energy needed to do something", "You need to put more effort into your studies."),
        VocabWord("Elder", "A person who is older than you", "We should always respect our elders."),
        VocabWord("Empty", "Containing nothing; having nothing inside", "The water bottle is empty, please fill it up."),
        VocabWord("Enemy", "A person who hates or fights another", "A true friend will never treat you like an enemy."),
        VocabWord("Enjoy", "To take pleasure in something", "I really enjoy playing cricket with my friends."),
        VocabWord("Enter", "To come or go into a place", "Please knock on the door before you enter the room."),
        VocabWord("Entire", "Whole or complete", "He ate the entire pizza by himself."),
        VocabWord("Equal", "Being the same in quantity, size, or value", "All citizens have equal rights under the law."),
        VocabWord("Escape", "To get free from danger or danger place", "The bird managed to escape from the cage."),
        VocabWord("Event", "Something important that happens", "The school sports event will start next week."),
        VocabWord("Exact", "Completely correct or accurate", "Can you tell me the exact time right now?"),
        VocabWord("Example", "Something that shows how a rule works", "Can you give me a simple example of this word?"),
        VocabWord("Excellent", "Extremely good or outstanding", "Wow! Your drawing skills are absolutely excellent."),
        VocabWord("Excite", "To make someone feel very happy or eager", "The news of the trip will excite all the kids."),
        VocabWord("Excuse", "A reason given to explain a mistake", "Stop making lazy excuses for being late."),
        VocabWord("Exercise", "Physical activity to stay healthy", "Daily exercise is good for your body and mind."),
        VocabWord("Experience", "Knowledge gained by doing things over time", "She has five years of experience in teaching."),
        VocabWord("Expert", "A person who knows a lot about a subject", "You should take advice from a computer expert."),
        VocabWord("Face", "To deal with a difficult situation", "We must face our problems with courage."),
        VocabWord("Fact", "Something that is completely true", "It is a fact that the Earth moves around the Sun."),
        VocabWord("Fail", "To not succeed in doing something", "Do not fear to fail, it is a part of learning."),
        VocabWord("Fair", "Just, right, or treating everyone equally", "The referee made a fair decision during the match."),
        VocabWord("False", "Not true; incorrect", "The statement given by the witness was false."),
        VocabWord("Famous", "Known by many people in many places", "Shah Rukh Khan is a very famous actor."),
        VocabWord("Far", "At a great distance away", "How far is the airport from your house?"),
        VocabWord("Fast", "Moving or happening at high speed", "Don't drive too fast on a crowded road."),
        VocabWord("Fault", "Responsibility for a mistake or bad thing", "It was my fault that I forgot the keys at home."),
        VocabWord("Favor", "A kind act done to help someone", "Can you do me a favor and hold this bag?"),
        VocabWord("Fear", "An unpleasant emotion caused by danger", "You must overcome your fear of public speaking."),
        VocabWord("Feed", "To give food to a person or animal", "Don't forget to feed the street dogs today."),
        VocabWord("Feeling", "An emotion like happiness, sadness, or anger", "I have a great feeling that today will be a good day."),
        VocabWord("Female", "Belonging to the sex that can give birth", "The company wants to hire more female employees."),
        VocabWord("Few", "A small number of things or people", "Only a few students were present in the class."),
        VocabWord("Fight", "To use physical force or words against someone", "Siblings often fight over TV remote controls."),
        VocabWord("Final", "Coming at the very end; last", "This is my final decision, I will not change it."),
        VocabWord("Gain", "To get or win something useful", "You will gain great experience by working here."),
        VocabWord("General", "Common or affecting most people", "This is a matter of general public interest."),
        VocabWord("Generous", "Willing to give money or help freely", "He is a generous man who helps the poor."),
        VocabWord("Gentle", "Mild, kind, or calm in behavior", "Be very gentle while holding the small puppy."),
        VocabWord("Gift", "A thing given to someone for free", "I received a beautiful gift on my birthday."),
        VocabWord("Glad", "Feeling happy or pleased", "I am very glad to hear about your success."),
        VocabWord("Goal", "Something you want to achieve", "My main goal is to speak English fluently."),
        VocabWord("Goodness", "The quality of being good or kind", "I still believe in the goodness of people."),
        VocabWord("Government", "The group of people who rule a country", "The government announced new rules today."),
        VocabWord("Grace", "Simple elegance or polite behavior", "She handled the difficult question with grace."),
        VocabWord("Grand", "Very large, beautiful, or impressive", "They live in a huge and grand house."),
        VocabWord("Grown", "Fully developed or mature", "Your children have grown up so fast."),
        VocabWord("Guard", "To protect against danger or attack", "Security personnel guard the building at night."),
        VocabWord("Guess", "To give an answer without being sure", "Can you guess the price of this smartphone?"),
        VocabWord("Guide", "To show the right way to someone", "The map will guide you through the new city."),
        VocabWord("Habit", "Something you do regularly or daily", "Reading books before bed is a wonderful habit."),
        VocabWord("Handsome", "Good-looking (usually used for men)", "He looks very handsome in that black suit."),
        VocabWord("Happen", "To take place or occur", "What will happen if we miss the last train?"),
        VocabWord("Hardly", "Almost not at all / Scarcely", "I could hardly sleep because of the noise."),
        VocabWord("Harm", "Physical hurt or damage", "Do not harm the birds or trees in the park."),
        VocabWord("Hate", "To dislike someone or something very much", "I completely hate waiting in long queues."),
        VocabWord("Hear", "To receive sound with your ears", "Did you hear the loud noise outside?"),
        VocabWord("Heavy", "Weighing a lot / Difficult to lift", "This box is too heavy for me to carry alone."),
        VocabWord("Helpful", "Providing useful help or advice", "The staff at the hotel counter was very helpful."),
        VocabWord("Hero", "A brave person admired for courage", "My father is my real-life hero and role model."),
        VocabWord("Hide", "To put something out of sight", "Where did you hide the car keys?"),
        VocabWord("High", "Extending far upward / Tall", "The mountains in this region are very high."),
        VocabWord("History", "The study of past events", "I love reading about ancient Indian history."),
        VocabWord("Hold", "To grip or carry something in hands", "Please hold my bag for a quick second."),
        VocabWord("Honest", "Telling the truth / Not cheating", "Always be honest with your friends and family."),
        VocabWord("Hope", "To want something good to happen", "I hope it does not rain during the match today."),
        VocabWord("Huge", "Extremely large in size or amount", "There is a huge crowd outside the cinema hall."),
        VocabWord("Human", "Relating to or characteristic of people", "Making mistakes is a normal part of human nature."),
        VocabWord("Humble", "Not proud / Modest and polite", "Despite being rich, he is very humble."),
        VocabWord("Hungry", "Feeling a need for food", "I am very hungry, let's order some food."),
        VocabWord("Hurry", "To move or act quickly", "Hurry up, or we will miss the bus to school."),
        VocabWord("Idea", "A thought, plan, or suggestion", "I have a great idea for our next holiday trip."),
        VocabWord("Identify", "To recognize who or what something is", "Can you identify the man standing in the photo?"),
        VocabWord("Important", "Of great value or significance", "Water is important for all living things on Earth."),
        VocabWord("Increase", "To make something greater or bigger", "The company wants to increase its sales this month."),
        VocabWord("Indeed", "In truth / Truly (used for emphasis)", "Thank you very much, that is very kind indeed."),
        VocabWord("Independent", "Free from outside control", "India became an independent nation in 1947."),
        VocabWord("Industry", "Economic activity involving factories", "The IT industry is growing very fast in India."),
        VocabWord("Injury", "Physical damage to the body", "He suffered a minor leg injury during the football game."),
        VocabWord("Innocent", "Not guilty of a crime or mistake", "The court proved that the young man was innocent."),
        VocabWord("Inside", "The inner part of something", "Please step inside the room and close the door."),
        VocabWord("Insist", "To demand something forcefully", "My friends insisted that I attend the party tonight."),
        VocabWord("Instead", "In place of something else", "I will have green tea instead of coffee today."),
        VocabWord("Intend", "To have a plan or purpose in mind", "I intend to finish this project work by tomorrow."),
        VocabWord("Interest", "A feeling of wanting to know or learn", "She has a deep interest in learning photography."),
        VocabWord("Introduce", "To tell someone your name or meet someone new", "Please introduce yourself to the new team."),
        VocabWord("Invent", "To create something completely new", "Who did invent the first electric bulb?"),
        VocabWord("Invite", "To ask someone to come to an event", "I want to invite all my friends to the party."),
        VocabWord("Join", "To become a member or connect together", "Would you like to join us for lunch today?"),
        VocabWord("Joke", "Something said or done to make people laugh", "He told a funny joke that made everyone laugh."),
        VocabWord("Judge", "To form an opinion about someone or something", "Don't judge a person by their clothes."),
        VocabWord("Jump", "To push oneself up into the air", "The cat tried to jump over the wall."),
        VocabWord("Just", "Exactly / Only a short time ago", "I have just finished my homework."),
        VocabWord("Keep", "To continue to have or hold something", "Please keep this book safely on the table."),
        VocabWord("Key", "A thing used to open a lock or find a solution", "Hard work is the key to success."),
        VocabWord("Kick", "To hit something with your foot", "The boy likes to kick the football in the park."),
        VocabWord("Kind", "Generous, helpful, and caring about others", "Thank you for your help, you are very kind."),
        VocabWord("King", "A male ruler of a country or kingdom", "The king ruled over his people with justice."),
        VocabWord("Kitchen", "A room where food is cooked", "My mother is cooking delicious food in the kitchen."),
        VocabWord("Knock", "To hit a door with knuckles to get attention", "Always knock before you open someone's door."),
        VocabWord("Knowledge", "Information and skills gained through learning", "Reading books helps to increase your knowledge."),
        VocabWord("Lack", "Not having enough of something", "The project failed due to a lack of money."),
        VocabWord("Lady", "A polite way to talk about a woman", "The old lady was walking slowly with a stick."),
        VocabWord("Lake", "A large area of water surrounded by land", "We went boating in the beautiful lake yesterday."),
        VocabWord("Land", "The solid part of the earth's surface", "The farmer owns a large piece of agricultural land."),
        VocabWord("Language", "System of communication used by people", "English is a widely spoken language in the world."),
        VocabWord("Large", "Big in size, amount, or number", "They have a very large family living together."),
        VocabWord("Last", "Coming after all others / Final", "Sunday is the last day of the week."),
        VocabWord("Late", "Happening after the correct or usual time", "Hurry up, otherwise we will be late for school."),
        VocabWord("Lately", "Recently / In the recent period of time", "I haven't seen him anywhere around lately."),
        VocabWord("Laugh", "To make sounds showing you are happy", "A good comedy movie always makes me laugh."),
        VocabWord("Law", "A set of rules made by the government", "Every citizen must follow the law of the land."),
        VocabWord("Lawyer", "A person whose job is to guide on law matters", "He hired a professional lawyer to handle his case."),
        VocabWord("Lazy", "Not wanting to work or use energy", "Don't be lazy, stand up and do some exercise."),
        VocabWord("Lead", "To show the way by going ahead", "A good captain knows how to lead the team."),
        VocabWord("Leader", "A person who leads or commands a group", "Mahatma Gandhi was a great visionary leader."),
        VocabWord("Learn", "To get knowledge or skill in something", "I want to learn how to drive a car."),
        VocabWord("Least", "Smallest in amount or importance", "Doing this work will take at least two hours."),
        VocabWord("Leave", "To go away from a place", "What time do you leave for your office daily?"),
        VocabWord("Legal", "Allowed or required by the law", "You must have a legal driving license to ride."),
        VocabWord("Less", "A smaller amount of something", "You should put less sugar in my tea, please."),
        VocabWord("Lesson", "A period of learning or teaching", "The teacher taught an important lesson today."),
        VocabWord("Let", "To give permission / Allow to do", "Please let me read this important news article."),
        VocabWord("Letter", "A written message sent to someone", "He wrote a formal letter to his school principal."),
        VocabWord("Level", "A position on a scale of amount or quality", "Try to play the game at a higher level now."),
        VocabWord("Library", "A place where books are kept to read", "Students go to the school library to study quietly."),
        VocabWord("Lie", "To say something that is not true", "It is a very bad habit to tell a lie."),
        VocabWord("Life", "The period from birth to death", "We should enjoy every single moment of our life."),
        VocabWord("Lift", "To raise something to a higher position", "This box is heavy, please help me to lift it."),
        VocabWord("Light", "Something that makes things visible / Not heavy", "Turn on the light, the room is very dark."),
        VocabWord("Like", "To find something pleasant or good", "I really like the flavor of ice cream you chose."),
        VocabWord("Likely", "Expected to happen / Probable", "It is likely to rain tonight, take an umbrella."),
        VocabWord("Limit", "A point beyond which you cannot go", "You must set a limit on your daily screen time."),
        VocabWord("Line", "A long, narrow mark or row of people", "Please stand in a straight line for the tickets."),
        VocabWord("Link", "A connection between two things", "Click on this internet link to open the website."),
        VocabWord("Listen", "To give attention to sound", "You should listen carefully to the instructions."),
        VocabWord("Live", "To remain alive or reside in a place", "I live in a beautiful city with my family."),
        VocabWord("Local", "Relating to a nearby area or neighborhood", "We buy fresh vegetables from the local market."),
        VocabWord("Lock", "To fasten something with a key", "Don't forget to lock the main gate tonight."),
        VocabWord("Lonely", "Unhappy because you are alone", "He felt very lonely when his friends moved away."),
        VocabWord("Long", "Measuring a great distance or time", "The road to the railway station is very long."),
        VocabWord("Look", "To direct your eyes toward something", "Please look at the blackboard during the class."),
        VocabWord("Lose", "To misplace something or fail to win", "Be careful with your wallet, don't lose it."),
        VocabWord("Loss", "The state of losing something or money", "The company suffered a heavy loss this year."),
        VocabWord("Loud", "Making a lot of noise", "The music from the speaker was too loud."),
        VocabWord("Love", "To feel deep affection or like very much", "Parents love their children unconditionally."),
        VocabWord("Low", "Not high or close to the ground", "The battery of my smartphone is very low."),
        VocabWord("Lucky", "Having good fortune or luck", "I am very lucky to have such helpful colleagues."),
        VocabWord("Machine", "An equipment with moving parts that does work", "The washing machine saves a lot of time and effort."),
        VocabWord("Mad", "Very angry or mentally unwell", "Why are you getting so mad at me for this?"),
        VocabWord("Main", "Most important or principal", "The main reason for his success is hard work."),
        VocabWord("Major", "Important, serious, or significant", "Lack of water is a major problem in this town."),
        VocabWord("Make", "To create, build, or produce something", "My mother knows how to make delicious cakes."),
        VocabWord("Male", "Relating to men or boys", "The company is looking for a male actor for the ad."),
        VocabWord("Manager", "A person responsible for controlling a group", "The bank manager solved my account problem quickly."),
        VocabWord("Manner", "The way in which something is done or behaves", "You should speak to everyone in a polite manner."),
        VocabWord("Many", "A large number of people or things", "There are many historical places to visit in India."),
        VocabWord("Map", "A visual drawing of an area or country", "The tourist used a digital map to find the route."),
        VocabWord("Mark", "A spot, sign, or line on something", "There is a dark mark on the white wall."),
        VocabWord("Market", "A place where things are bought and sold", "The local market is very crowded on weekends."),
        VocabWord("Marry", "To legally become husband and wife", "They decided to marry after completing their studies."),
        VocabWord("Match", "To be equal or fit together perfectly", "Your black shoes match nicely with your suit."),
        VocabWord("Matter", "A subject or situation under consideration", "Don't worry, it is a very simple matter."),
        VocabWord("Maximum", "The highest amount or level possible", "The maximum speed limit on this highway is 80."),
        VocabWord("Maybe", "Perhaps / Possibly true", "Maybe it will rain today, so take your umbrella."),
        VocabWord("Meal", "Food eaten at a certain time of day", "Breakfast is the most important meal of the day."),
        VocabWord("Mean", "To have a specific meaning / Not kind", "What do you mean by this statement?"),
        VocabWord("Meaning", "The message or idea intended", "Can you explain the meaning of this English word?"),
        VocabWord("Measure", "To find the size, weight, or amount", "Use a scale to measure the length of the table."),
        VocabWord("Medicine", "Substance used to treat illness or pain", "Take this medicine twice a day after meals."),
        VocabWord("Meet", "To come together with someone intentionally", "I am going to meet my childhood friend today."),
        VocabWord("Meeting", "An assembly of people for discussion", "The company director called an urgent meeting."),
        VocabWord("Member", "A person belonging to a group or family", "He is the youngest member of our sports club."),
        VocabWord("Memory", "The ability to remember things clearly", "The old photos brought back many happy memories."),
        VocabWord("Mention", "To speak or write about something briefly", "Did he mention the date of the upcoming exam?"),
        VocabWord("Message", "Written or spoken information sent to someone", "I sent a text message to inform him about the plan."),
        VocabWord("Method", "A specific way of doing something", "What is the easiest method to solve this puzzle?"),
        VocabWord("Middle", "The center point or part of something", "The teacher stood in the middle of the classroom."),
        VocabWord("Might", "Used to express possibility", "It might take some time to complete this work."),
        VocabWord("Mind", "The part of a person that thinks and feels", "Keep your mind calm while making big decisions."),
        VocabWord("Minimum", "The smallest amount or level possible", "The minimum age to vote in India is 18 years."),
        VocabWord("Minor", "Small, not serious, or less important", "Fortunately, it was just a minor car accident."),
        VocabWord("Minute", "A unit of time equal to 60 seconds", "Please wait for a minute, I am coming out."),
        VocabWord("Mirror", "A glass surface that reflects an image", "She looked at herself in the mirror before leaving."),
        VocabWord("Miss", "To fail to catch something / To feel sad without someone", "I miss my parents when I stay away from home."),
        VocabWord("Mix", "To combine things together", "Mix the sugar and water until it dissolves."),
        VocabWord("Modern", "Relating to the present time; new", "This building has a very modern design."),
        VocabWord("Moment", "A very short period of time", "Please wait for a moment, I am busy right now."),
        VocabWord("Money", "Coins or banknotes used to buy things", "He saved enough money to buy a new bicycle."),
        VocabWord("Month", "One of the 12 periods of time in a year", "January is the first month of the year."),
        VocabWord("Mood", "The way you are feeling at a particular time", "Good music always lifts my mood."),
        VocabWord("Morning", "The early part of the day", "I like to go for a run in the morning."),
        VocabWord("Most", "Greatest in amount or degree", "Most of the students passed the English test."),
        VocabWord("Mountain", "A very high hill", "Mount Everest is the highest mountain in the world."),
        VocabWord("Move", "To change position or place", "Please move this chair to the other room."),
        VocabWord("Movement", "An act of changing physical position", "The sudden movement of the snake scared me."),
        VocabWord("Much", "A large amount of something", "Thank you very much, I appreciate your help."),
        VocabWord("Music", "Vocal or instrumental sounds", "Listening to soft music helps me relax."),
        VocabWord("Name", "A word by which a person or thing is known", "What is the name of your new puppy?"),
        VocabWord("Narrow", "Small in width; not wide", "The car cannot pass through this narrow street."),
        VocabWord("Nation", "A country or large group of people", "India is a fast-developing nation."),
        VocabWord("Native", "Associated with the place of one's birth", "Hindi is my native language."),
        VocabWord("Natural", "Made by nature, not by humans", "Green vegetables are a natural source of vitamins."),
        VocabWord("Nature", "The physical world including plants and animals", "I love spending time close to nature."),
        VocabWord("Near", "Close to something; not far away", "My house is very near to the railway station."),
        VocabWord("Nearly", "Almost / Very close to", "The work is nearly finished, just ten minutes more."),
        VocabWord("Neat", "Clean and organized", "Always keep your study desk neat and tidy."),
        VocabWord("Neck", "The part of the body connecting head to shoulders", "He wears a silver chain around his neck."),
        VocabWord("Need", "Require something because it is essential", "I need some water, I am very thirsty."),
        VocabWord("Negative", "Not hopeful or positive / Saying no", "Try to stay away from negative thoughts."),
        VocabWord("Neighbor", "A person living near or next to you", "Our neighbor is very friendly and helpful."),
        VocabWord("Neither", "Not the one nor the other", "Neither of the two answers is correct."),
        VocabWord("Nervous", "Feeling worried or anxious", "He felt nervous before going on the stage."),
        VocabWord("Never", "At no time / Not ever", "You should never break a promise made to a friend."),
        VocabWord("New", "Not old; recently made or bought", "Look at my new watch, my brother gifted it."),
        VocabWord("News", "New information about recent events", "I watch the evening news to stay updated."),
        VocabWord("Next", "Coming immediately after", "The next train will arrive in fifteen minutes."),
        VocabWord("Nice", "Pleasant, agreeable, or kind", "It was very nice meeting you after so long."),
        VocabWord("Night", "The period of darkness after sunset", "The stars look very bright in the sky at night."),
        VocabWord("Noise", "A sound, especially one that is loud or unpleasant", "The kids are making a lot of noise in the class."),
        VocabWord("None", "Not any / No one", "None of my friends attended the party."),
        VocabWord("Normal", "Usual, typical, or expected", "It is completely normal to make mistakes while learning."),
        VocabWord("North", "One of the four main directions", "The Himalayan mountains are in the north of India."),
        VocabWord("Nose", "The part of the face used for smelling and breathing", "The dog has a very strong sense of smell in its nose."),
        VocabWord("Note", "A short written message to remember something", "He wrote a quick note on the paper."),
        VocabWord("Nothing", "Not anything / Zero things", "Don't worry, nothing is wrong here."),
        VocabWord("Now", "At the present time / Right away", "You should start studying for exams now."),
        VocabWord("Number", "A mathematical value used for counting", "Can you give me your contact number, please?"),
        VocabWord("Obey", "To follow orders or rules", "Children should obey their parents and teachers."),
        VocabWord("Object", "A material thing that can be seen and touched", "There is a strange object lying on the ground."),
        VocabWord("Ocean", "A very large expanse of sea", "The Pacific Ocean is the largest ocean in the world."),
        VocabWord("Offer", "To present something to be accepted or refused", "The company gave him a great job offer."),
        VocabWord("Office", "A room or building where people work", "My father goes to his office at 9 AM daily."),
        VocabWord("Officer", "A person holding a position of authority", "The police officer helped us find the lost bag."),
        VocabWord("Often", "Many times / Frequently", "I often go to the park for an evening walk."),
        VocabWord("Pain", "A feeling of physical suffering", "He has a mild pain in his lower back."),
        VocabWord("Parent", "A father or a mother", "Every parent wants a bright future for their child."),
        VocabWord("Park", "A public green area for recreation", "Children love to play football in the park."),
        VocabWord("Part", "A piece or section of something", "Reading is an important part of learning English."),
        VocabWord("Partner", "A person who takes part in an activity with another", "You need a practice partner to improve your speaking."),
        VocabWord("Party", "A social gathering for celebration", "We are invited to a birthday party tonight."),
        VocabWord("Pass", "To move past something / Clear an exam", "Drive carefully when you pass through the narrow tunnel."),
        VocabWord("Past", "The time before the present", "Forget the past and focus on your bright future."),
        VocabWord("Patient", "Able to accept delays without getting angry / A sick person", "Please be patient, the results will be announced soon."),
        VocabWord("Pay", "To give money for goods or services", "You can pay the bill using your smartphone."),
        VocabWord("Peace", "Freedom from disturbance; quiet and calm", "I love the peace and quiet of the countryside."),
        VocabWord("Perfect", "Having no mistakes or flaws; excellent", "Practice makes a man perfect in any skill."),
        VocabWord("Perform", "To carry out a task or action", "The dance group will perform on the stage tomorrow."),
        VocabWord("Person", "A human being regarded as an individual", "He is a very kind and helpful person."),
        VocabWord("Pick", "To choose or take something up", "Please pick up the phone, someone is calling."),
        VocabWord("Piece", "A portion or bit of something", "Can I have a small piece of that chocolate cake?"),
        VocabWord("Place", "A particular position or area", "Indore is a very clean and beautiful place to live."),
        VocabWord("Plan", "A detailed proposal for doing something", "What is your plan for the upcoming weekend?"),
        VocabWord("Plant", "A living organism like trees or shrubs", "Remember to water the indoor plants daily."),
        VocabWord("Plastic", "A synthetic material shaped when soft", "We should avoid using single use plastic bags."),
        VocabWord("Plate", "A flat dish from which food is eaten", "Please put some fresh salad on my plate."),
        VocabWord("Play", "To engage in activity for enjoyment", "The kids like to play cricket in the evening."),
        VocabWord("Pleasant", "Giving a sense of happy satisfaction", "The weather today is very pleasant and cool."),
        VocabWord("Plenty", "A large or sufficient amount", "Don't worry, we have plenty of time to reach the station."),
        VocabWord("Point", "A sharp end / An idea or argument", "You made a very valid point during the discussion."),
        VocabWord("Police", "The civil force responsible for maintaining law", "The police caught the thief within an hour."),
        VocabWord("Polite", "Having good manners and respect for others", "Always use a polite tone when talking to clients."),
        VocabWord("Poor", "Lacking sufficient money to live comfortably", "The NGO distributes free blankets to poor people."),
        VocabWord("Popular", "Liked or admired by many people", "This local restaurant is very popular for its snacks."),
        VocabWord("Position", "A place where someone or something is located", "He secured the top position in the final examination."),
        VocabWord("Positive", "Full of hope and confidence", "Try to maintain a positive attitude in difficult times."),
        VocabWord("Possible", "Able to be done or achieved", "Is it possible to finish this report by 5 PM?"),
        VocabWord("Postpone", "To cause something to take place at a later time", "They decided to postpone the meeting until Monday."),
        VocabWord("Pour", "To flow or cause to flow in a stream", "Please pour some hot tea into my cup."),
        VocabWord("Power", "The ability or capacity to do something", "Knowledge gives you the power to change your life."),
        VocabWord("Practice", "Doing something regularly to improve", "Daily practice is necessary to speak fluent English."),
        VocabWord("Praise", "To express approval or admiration", "Teachers always praise hard-working students."),
        VocabWord("Prefer", "To like one thing better than another", "I prefer drinking hot tea over cold coffee."),
        VocabWord("Prepare", "To make something ready for use", "Give yourself enough time to prepare for the interview."),
        VocabWord("Presence", "The state of being present in a place", "Your presence at the wedding is very important to us."),
        VocabWord("Present", "Existing or occurring now / A gift", "At present, he is working as a software developer."),
        VocabWord("President", "The elected head of a republican state", "The president addressed the entire nation today."),
        VocabWord("Press", "To apply pressure or push a button", "Please press the green button to start the machine."),
        VocabWord("Pretty", "Attractive in a delicate way / Fairly or moderately", "The flowers in the garden look very pretty."),
        VocabWord("Prevent", "To stop something from happening", "Regular exercise can help prevent many health issues."),
        VocabWord("Price", "The amount of money expected for something", "What is the exact price of this new smartphone?"),
        VocabWord("Pride", "A feeling of deep pleasure or satisfaction", "He took great pride in his son's achievements."),
        VocabWord("Private", "Belonging to one particular person; not public", "This is a private property, entry is not allowed."),
        VocabWord("Prize", "A reward given to the winner of a contest", "She won the first prize in the singing competition."),
        VocabWord("Problem", "A matter or situation regarded as unwelcome", "Don't worry, every problem has a simple solution.")
    )
}
